---
- name: Converge
  become: True
  hosts: all
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - name: install python mysqldb for Ansible
      apt:
        pkg: python-mysqldb
        state: installed
        update_cache: no
      changed_when: False

- name: Converge
  become: yes
  hosts: all
  vars:
    mariadb_enabled: yes
    mariadb_root_password: molecule
    mariadb_bind_address: 0.0.0.0
  roles:
    - role: role-mariadb
