- name: install mariadb packages
  apt:
    name:
      - python3-mysqldb
      - "mariadb-server-{{ mariadb_version }}"
      - "mariadb-client-{{ mariadb_version }}"
    state: present

- name: check for empty root password
  mysql_user:
    name: root
    password: ''
    check_implicit_admin: True
    login_user: root
    login_password: ''
    state: present
  ignore_errors: True
  register: mariadb_default_password

- name: set root password
  mysql_user:
    name: root
    password: '{{ mariadb_root_password }}'
    check_implicit_admin: True
    login_user: root
    login_password: ''
    state: present
  when: mariadb_default_password is succeeded

- name: template mariadb config files
  template:
    src: "templates/{{ mariadb_config_file }}.j2"
    dest: "{{ mariadb_config_file }}"
    owner: root
    group: mysql
    mode: 0640
  with_items:
    - /etc/mysql/mariadb.conf.d/98-ansible.cnf
    - /etc/mysql/mariadb.conf.d/99-custom.cnf
    - /etc/mysql/mariadb.cnf
  loop_control:
    loop_var: mariadb_config_file
  notify: restart mariadb

- name: template /root/.my.cnf
  copy:
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400
    content: |
      [client]
      user=root
      password={{ mariadb_root_password }}



- name: create mariadb databases
  mysql_db:
    name: "{{ mariadb_database['name'] }}"
    state: "{{ mariadb_database['state'] | default('present') }}"
  with_items: "{{ mariadb_databases }}"
  loop_control:
    loop_var: mariadb_database
  when: mariadb_databases is defined

- name: create mariadb users with grants
  mysql_user:
    name: "{{ mariadb_user['name'] }}"
    state: "{{ mariadb_user['state'] | default('present') }}"
    host: "{{ mariadb_user['host'] | default('localhost') }}"
    password: "{{ mariadb_user['password'] }}"
    priv: "{{ mariadb_user['priv'] }}"
  when: mariadb_users is defined
  with_items: "{{ mariadb_users }}"
  loop_control:
    loop_var: mariadb_user
