- name: check the MySQL root password
  mysql_user:
    name: root
    password: ''
    check_implicit_admin: yes
    login_user: root
    login_password: ''
    state: present
  ignore_errors: yes
  register: mariadb_default_pw

- name: set MySQL root password
  when: mariadb_default_pw is succeeded
  mysql_user:
    name: root
    password: '{{ mariadb_root_password }}'
    check_implicit_admin: yes
    login_user: root
    login_password: ''
    state: present

- name: deploy /etc/mysql/mariadb.conf.d/50-server.cnf
  template:
    src: etc/mysql/mariadb.conf.d/50-server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
  notify: restart mariadb

- name: create a /root/.my.cnf
  copy:
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400
    content: |
      [client]
      user=root
      password={{ mariadb_root_password }}

- name: create mariadb databases
  mysql_db:
    name: "{{ mysql_database['name'] }}"
    state: "{{ mysql_database['state'] | default('present') }}"
  with_items: "{{ mysql_databases }}"
  loop_control:
    loop_var: mysql_database
  when: mysql_databases is defined

- name: create mariadb users with grants
  mysql_user:
    name: "{{ mysql_user['name'] }}"
    state: "{{ mysql_user['host'] | default('present') }}"
    host: "{{ mysql_user['host'] | default('localhost') }}"
    password: "{{ mysql_user['password'] }}"
    priv: "{{ mysql_user['priv'] }}"
  when: mysql_users is defined
  with_items: "{{ mysql_users }}"
  loop_control:
    loop_var: mysql_user
