---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: stretch-master
    groups:
      - masters
    box: bento/debian-9.0
    interfaces:
      - network_name: private_network
        type: static
        auto_config: False
        ip: 10.44.0.1/24
  - name: stretch-slave
    groups:
      - slaves
    box: bento/debian-9.0
    interfaces:
      - network_name: private_network
        type: static
        auto_config: False
        ip: 10.44.0.2/24
provisioner:
  name: ansible
  playbooks:
    side_effect: side_effect.yml
  connection_options:
    ansible_become: true
  lint:
    name: ansible-lint
scenario:
  name: replication
verifier:
  name: testinfra
  lint:
    name: flake8
