---
- name: "Converge: Masters"
  hosts: stretch-master,xenial-master
  become: True
  vars:
    mariadb_root_password: molecule
    mariadb_bind_address: 0.0.0.0
    mariadb_server_id: 10
    mariadb_log_bin: /var/log/mysql/mysql-bin.log
  roles:
    - role: role-mariadb

- name: "Converge: Prepare masters"
  hosts: stretch-master,xenial-master
  become: yes
  tasks:
    - name: Create replication user
      mariadb_user:
        name: replication
        password: replication
        host: '%'
        priv: "*.*:REPLICATION SLAVE"
        login_user: root
        login_password: molecule
        state: present
    - name: Flush privileges
      command: mysql -uroot -pmolecule -Bse "flush privileges;"
      changed_when: False
    - name: Create dump
      shell: mysqldump -uroot -pmolecule --all-databases --master-data --single-transaction --gtid | gzip > /root/repl.sql.gz
      changed_when: False
    - name: Fetch dump
      fetch:
        src: /root/repl.sql.gz
        dest: /tmp/fetched/root/{{ ansible_lsb.codename }}.sql.gz
        flat: yes
        fail_on_missing: yes
      changed_when: False

- name: "Converge: Slaves"
  hosts: stretch-slave,xenial-slave
  become: True
  vars:
    mariadb_root_password: molecule
    mariadb_server_id: 20
  roles:
    - role: role-mariadb
  tasks:
    - name: Upload dump
      copy:
        src: /tmp/fetched/root/{{ ansible_lsb.codename }}.sql.gz
        dest: /root/repl.sql.gz
        owner: root
        group: root
      changed_when: False

- name: "Converge: Initialize Debian replication"
  hosts: stretch-slave
  become: yes
  tasks:
    - name: Stop slave if running
      command: mysql -uroot -pmolecule -Bse "stop slave;"
      changed_when: False
    - name: Import initial state from master
      shell: cat /root/repl.sql.gz | gzip -d | mysql -uroot -pmolecule
      changed_when: False
    - name: Configure master position
      command: mysql -uroot -pmolecule -Bse "change master to master_host = '10.44.0.1', master_user = 'replication', master_password = 'replication';"
      changed_when: False
    - name: Start slave
      command: mysql -uroot -pmolecule -Bse "start slave;"
      changed_when: False

- name: "Converge: Initialize Ubuntu replication"
  hosts: xenial-slave
  become: yes
  tasks:
    - name: Stop slave if running
      command: mysql -uroot -pmolecule -Bse "stop slave;"
      changed_when: False
    - name: Import initial state from master
      shell: cat /root/repl.sql.gz | gzip -d | mysql -uroot -pmolecule
      changed_when: False
    - name: Configure master position
      command: mysql -uroot -pmolecule -Bse "change master to master_host = '10.45.0.1', master_user = 'replication', master_password = 'replication';"
      changed_when: False
    - name: Start slave
      command: mysql -uroot -pmolecule -Bse "start slave;"
      changed_when: False
