---
# Setup of replication requires connectivity, which is bugging in Vagrant+VirtualBox.
- name: "Work around VirtualBox` connectivity issue"
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping Debian Master
      command: ping -c2 -t30 10.44.0.1
      changed_when: no
      failed_when: no
    - name: Ping Debian Slave
      command: ping -c2 -t30 10.44.0.2
      changed_when: no
      failed_when: no
    - name: Ping Ubuntu Master
      command: ping -c2 -t30 10.45.0.1
      changed_when: no
      failed_when: no
    - name: Ping Ubuntu Slave
      command: ping -c2 -t30 10.45.0.2
      changed_when: no
      failed_when: no

- name: Side-Effect
  hosts: slaves
  become: yes
  tasks:
    - name: reload mysql daemon
      systemd:
        name: mysql
        state: restarted
